snowsql_config_path = "~/.snowsql/config"
snowsql_connection_name = "dev"

[default]
input_parameters = "(estimated_shipment_value float, manifest_quantity float)"
return_type = "float"
file = "app.zip"
name = "price_per_manifest_udf"
handler = "app.main"
execute_as_caller = true

[dev]
database = "DB_DAMG7245_TEAM7"
schema = "ANALYTICS"
warehouse = "WH_DAMG7245_TEAM7"
role = "ROLE_DAMG7245_TEAM7"
overwrite = true
