USE ROLE ACCOUNTADMIN;

-- Roles
SET MY_USER = CURRENT_USER();
CREATE OR REPLACE ROLE ROLE_DAMG7245_TEAM7;
GRANT ROLE ROLE_DAMG7245_TEAM7 TO ROLE SYSADMIN;
GRANT ROLE ROLE_DAMG7245_TEAM7 TO USER IDENTIFIER($MY_USER);

GRANT EXECUTE TASK ON ACCOUNT TO ROLE ROLE_DAMG7245_TEAM7;
GRANT MONITOR EXECUTION ON ACCOUNT TO ROLE ROLE_DAMG7245_TEAM7;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE ROLE_DAMG7245_TEAM7;

-- Databases
CREATE OR REPLACE DATABASE DB_DAMG7245_TEAM7;
GRANT OWNERSHIP ON DATABASE DB_DAMG7245_TEAM7 TO ROLE ROLE_DAMG7245_TEAM7;

-- Warehouses
CREATE OR REPLACE WAREHOUSE WH_DAMG7245_TEAM7 WAREHOUSE_SIZE = XSMALL, AUTO_SUSPEND = 300, AUTO_RESUME= TRUE;
GRANT OWNERSHIP ON WAREHOUSE WH_DAMG7245_TEAM7 TO ROLE ROLE_DAMG7245_TEAM7;


-- ----------------------------------------------------------------------------
-- Step #3: Create the database level objects
-- ----------------------------------------------------------------------------
USE ROLE ROLE_DAMG7245_TEAM7;
USE WAREHOUSE WH_DAMG7245_TEAM7;
USE DATABASE DB_DAMG7245_TEAM7;

-- Schemas
CREATE OR REPLACE SCHEMA EXTERNAL;
CREATE OR REPLACE SCHEMA HARMONIZED;
CREATE OR REPLACE SCHEMA ANALYTICS;
